// 1. var, let, const ilə 3 dəyişən yarat və alert ilə göstər

var yas = 16;
let şəhər = "Bakı";
const olkə = "Azərbaycan";

alert(yas);
alert(şəhər);
alert(olkə);


// müəllim 2 cini başa düşmədim deyə eliyə bilmədim sabah izah edərsizdə

// 3. İstədiyin meyvənin adını let dəyişənində saxla
// və document.write ilə ekrana yaz

let meyve = "Alma";

document.write("Meyvə: " + meyve +"<br>");


// 4. var ilə eyni adlı iki dəyişən yarat

var eded = 10;
var eded = 20;

console.log("var nəticəsi:", eded);


// Eyni kodu let ilə yaz

let reqem = 40;


// 5. Öz adını let dəyişənində saxla
// və alert ilə salamlama mesajı çıxart

let ad = "Tunar";

alert("Salam, " + ad + "!");